name: Hello World!

on:
  push:
    branches:
      - master
      # note that your "main" branch mght be called main instead of master

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: cd directory && echo 'boboddy  BO BODDY' && flyctl deploy --remote-only