name: Hello world!

on:
  push:
    branches:
      - master

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  jobs:
    deploy:
      name: Deploy app
      runs-on: ubuntu-latest
      steps:
        - name: Say hello
          run: |
            echo "Hellow guys"