name: Hello world!

on:
  push:
    branches:
      - master

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  jobs:
    hello_world_job:
      runs-on: ubuntu-20.04
      steps:
        - name: Say hello
          run: |
            echo "Hello World!"